### ISSUE TITLE
Can't receive notification when app running in foreground

### ISSUE THREAD

**Issue by shilohchis** [evollu/react-native-fcm#345] opened 2017-03-09 15:05 UTC
I used RN 41, react-native-fcm 6.1.0, Android 5 device,
I already followed the instruction based on []https://github.com/evollu/react-native-fcm/blob/master/README.md
It's run smoothly when app not open, when app running the notifications look like not receive by the fcm.. Is there any way to show the notification when the app running in foreground?

**Comment by nvbn** [comment] 2017-03-16 10:15
I have the same issue, when app is in background it works, but when app in foreground it's not. Code to reproduce:
```javascript
FCM.requestPermissions();

const notification = await FCM.getInitialNotification();
// Prints notification received in background:
console.log(notification);

FCM.on(
  FCMEvent.Notification,
  // Doesn't print anything:
  (notification) => console.log(notification),
);
```

**Comment by nvbn** [comment] 2017-03-27 13:01
This can be easily fixed by just adding to `AndroidManifest.xml`:
```
<service android:name="com.evollu.react.fcm.MessagingService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
    </intent-filter>
</service>

<service android:name="com.evollu.react.fcm.InstanceIdService" android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>
```

And it's already in readme.

**Comment by evollu** [comment] 2017-04-11 20:03
@shilohchis is this issue fixed?

**Comment by rishabhbhatia** [comment] 2017-04-12 10:29
@nvbn Hi Vladimir, i have this code present under my AndroidManifest file & still i face the same issue. My send local notification code is  
```
_sendLocalNotification = (notif) => {
      FCM.presentLocalNotification({
            title: notif.title,                     // as FCM payload
            body: notif.body,                    // as FCM payload (required)
            priority: "high",                                   // as FCM payload
            click_action: "ACTION",                             // as FCM payload
            auto_cancel: true,                                  // Android only (default true)
            vibrate: 300,                                       // Android only default: 300, no vibration if you pass null
            lights: true,                                       // Android only, LED blinking (default false)
            show_in_foreground: true,                           // show notification when app is in foreground (local & remote)
            local: true                                  
        })
    }
```

While app is background the notification works fine, but when in foreground i receive the FCM notification, send notification function is called but it's not reflecting in my notification panel.

**Comment by evollu** [comment] 2017-04-12 13:19
@rishabhbhatia do you get callback from `FCM.on`?

**Comment by rishabhbhatia** [comment] 2017-04-12 15:21
@evollu Yes, i get a callback in function 
```
 FCM.on(FCMEvent.Notification, async (notif)
```

and _sendLocalNotification is called but it doesn't reflect in the notification tray if app's in front.

**Comment by evollu** [comment] 2017-04-12 15:47
do you have these 2 receiver in manifest?
```
<receiver android:name="com.evollu.react.fcm.FIRLocalMessagingPublisher"/>
        <receiver android:enabled="true" android:exported="true"  android:name="com.evollu.react.fcm.FIRSystemBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
```

**Comment by rishabhbhatia** [comment] 2017-04-12 15:57
@evollu Yes, i do.

**Comment by evollu** [comment] 2017-04-12 16:00
do you have android studio or any other android IDE?
if you try add break point at `FIRLocalMessagingHelper.java` line 177 and see if it going into the `if` condition

**Comment by rishabhbhatia** [comment] 2017-04-12 16:30
So with breakpoints i found out in `FIRLocalMessagingHelper.java ` line 67 
```
if (bundle.getString("body") == null) {
     return;
}
```
here the return is executing as it's saying body is null, which i verified from the bundle value was. Here's the bundle at this point
```
Bundle[{auto_cancel=true, priority=high, lights=true, id=xxx, local=true, click_action=ACTION, vibrate=300.0, local_notification=true, show_in_foreground=true}]
```

Here i logged my notification it has body present in it when im sending from firebase console 
```
{"fcm":{"action":null,"tag":null,"icon":null,"color":null,"body":"Welcome to Firebase!","title":null}}
```

**Comment by rishabhbhatia** [comment] 2017-04-12 16:47
Thanks Libin for telling the function to debug, i resolved the problem. Body was being passed as null & it was returning from function without warnings. I changed my structure and it works. Receiving some errors i'll try to resolve myself. One is an exception being throw at missing vibrate value in FIRLocalMessagingHelper here 
```
 //vibrate
            if(bundle.containsKey("vibrate")){
                long vibrate = bundle.getLong("vibrate", Math.round(bundle.getDouble("vibrate", bundle.getInt("vibrate"))));
```
Exception ->
```
W/Bundle: Key vibrate expected Integer but value was a java.lang.Double.  The default value 0 was returned.
04-12 22:09:18.616 15681-15747/com.alertsreact W/Bundle: Attempt to cast generated internal exception:
                                                         java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
                                                             at android.os.BaseBundle.getInt(BaseBundle.java:800)
                                                             at android.os.BaseBundle.getInt(BaseBundle.java:782)
                                                             at com.evollu.react.fcm.FIRLocalMessagingHelper.sendNotification(FIRLocalMessagingHelper.java:159)
                                                             at com.evollu.react.fcm.FIRMessagingModule.presentLocalNotification(FIRMessagingModule.java:80)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                             at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
                                                             at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                             at java.lang.Thread.run(Thread.java:818)
04-12 22:09:18.616 15681-15747/com.alertsreact W/Bundle: Key vibrate expected Long but value was a java.lang.Double.  The default value 300 was returned.
04-12 22:09:18.616 15681-15747/com.alertsreact W/Bundle: Attempt to cast generated internal exception:
                                                         java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
                                                             at android.os.BaseBundle.getLong(BaseBundle.java:834)
                                                             at com.evollu.react.fcm.FIRLocalMessagingHelper.sendNotification(FIRLocalMessagingHelper.java:159)
                                                             at com.evollu.react.fcm.FIRMessagingModule.presentLocalNotification(FIRMessagingModule.java:80)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                             at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
                                                             at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                             at java.lang.Thread.run(Thread.java:818)
```

**Comment by evollu** [comment] 2017-04-12 17:25
try place the vibrate line with
`long vibrate = bundle.getDouble("vibrate", 0)`?

**Comment by rishabhbhatia** [comment] 2017-04-13 06:36
Hi i used long vibrate = Math.round(bundle.getDouble("vibrate", defaultValue)) Works fine now, thanks!

**Comment by Holox** [comment] 2017-04-30 20:10
@rishabhbhatia I have the same (empty body) problem. So what exactly did you change in your structure to make it work?

**Comment by rishabhbhatia** [comment] 2017-05-01 10:25
@Holox I logged the data being passed to sendLocalNotification and body was missing under it, for me it was just the incorrect variable being passed below. Changing how i access body variable solved it for me. Attaching a snippet maybe it helps
 ```
// this is notification coming from fcm
 if (notif.fcm) {

        this.title = notif.fcm.title
        this.body = notif.fcm.body

        this.sendLocalNotification(this.title, this.body)
      }
```
I logged and verified under class FIRLocalMessagingHelper.java in studio, hopefully it helps you.

**Comment by AkshayKomarla** [comment] 2017-05-26 05:41
this was resolved for me when i removed **await someAsyncCall();** from **FCM.on(FCMEvent.Notification..**

**Comment by JCMais** [comment] 2017-06-08 02:14
In my case the icon being incorrect also made the notification not appear on foreground.

**Comment by tocttou** [comment] 2017-06-24 15:17
Same issue here using Firebase Console.

**Comment by SuhairZain** [comment] 2017-07-11 08:06
Hi,
Messages sent from firebase console isn't received if the app is in the foreground, but it works perfectly when backgrounded.

I'm not using Local notifications but I tried adding the two receivers to see if that was the problem. That doesn't fix it. Has anyone found a solution to this?

**Comment by SuhairZain** [comment] 2017-07-13 15:10
Hi,
As per the [README](https://github.com/evollu/react-native-fcm#behaviour-when-sending-notification-and-data-payload-through-gcm), a remote notification won't be shown on Android if the app is in the foreground. But this is a required feature for us to push updates to the client. Is there any way to get notifications while the app is in the foreground?

**Comment by evollu** [comment] 2017-07-13 15:20
you can send a data notification like this. This lib will create a notif for you
```
{
   data: {
     custom_notification: {
         title: 'a', body: 'b', show_in_foreground: true
     }
   }
}
```

**Comment by SuhairZain** [comment] 2017-07-13 15:23
Hi @evollu ,
Thanks a lot for the reply. Are the title and body fields required? If I have to pass some parameter to the app, can I make the data so:
```json
"data": {
    "custom_notification": {
        "notifType": "PRODUCT_DISPLAY",
        "productId": "1234",
        "show_in_foreground": true
    }
}
```

**Comment by alexhoo** [comment] 2017-09-29 15:07
Also you need to send this data serialized and parse it by the time you receive it.

**Comment by evollu** [comment] 2017-09-30 17:31
@SuhairZain yes, title body required

**Comment by evollu** [comment] 2017-09-30 17:34
closing the issue because original issue seems solved

**Closed by evollu** 2017-09-30 17:34 UTC

**Comment by lulzimfazlija** [comment] 2018-02-01 23:40
is this really solving the problem? what exactly is modified?

**Comment by lulzimfazlija** [comment] 2018-02-01 23:40
@evollu @rishabhbhatia

**Comment by SuhairZain** [comment] 2018-02-02 03:49
Hi @lulzimfazlija I think this could be what they meant by that it's solved: https://github.com/evollu/react-native-fcm/issues/345#issuecomment-315110574

**Comment by lulzimfazlija** [comment] 2018-02-02 09:28
@SuhairZain 

`  FCM.presentLocalNotification({
            custom_notification: {
                title: 'a', body: 'b', show_in_foreground: true
            }
        });`

Is this how it should look like the code? Can you pls post some code if it worked for you!

**Comment by SuhairZain** [comment] 2018-02-02 14:30
@lulzimfazlija 
I'm unable to post the code since it was a closed source project. What I did was, I set up a backend server to send the notifications and I made the notification payload data similar to the one in the aforementioned comment. I think what this library does is, when it comes across a notification with show_in_background set to true in its data payload, it shows the notification even when the app is backgrounded. I hope I've made it clear to you.

**Comment by evollu** [comment] 2018-02-05 14:50
@lulzimfazlija you don't need to wrap things in custom_notification if it is local notificaiton
just do 
```
FCM.presentLocalNotification({title: 'a', body: 'b', show_in_foreground: true }})
```

**Comment by xemasiv** [comment] 2018-02-11 14:29
react-native@0.50.4
react-native-fcm@13.1.0

Following fixed it for me:

* Using `classpath 'com.google.gms:google-services:3.2.0'` on project-level `build.gradle`
* Using `compile 'com.google.firebase:firebase-core:11.8.0'` on app-level `build.gradle`
* Adding `compile 'com.google.firebase:firebase-messaging:11.8.0'` on app-level `build.gradle`

**Comment by SatishMavani** [comment] 2018-08-13 11:27
it's not working with all the solution above and not able to see a notification when my app is in the foreground, any help?

**Comment by razibchamp** [comment] 2018-09-23 06:40
hi
