### ISSUE TITLE
Xcode9 Build failed ['exception' file not found String.h]

### ISSUE THREAD

**Issue by NoerNova** [evollu/react-native-fcm#606] opened 2017-10-11 03:12 UTC
![untitled2](https://user-images.githubusercontent.com/9565672/31420445-b79f62ca-ae6b-11e7-8924-d35a0faf82d6.png)

on Xcode9
react-native-fcm": "^10.0.1"
try to build on iPhone Device with iOS 11

![untitled](https://user-images.githubusercontent.com/9565672/31420580-9563a06c-ae6c-11e7-908b-a1c44af33d31.png)

**Comment by DreamBuddy** [comment] 2017-10-31 02:25
I have the same issue

**Comment by evollu** [comment] 2017-10-31 14:01
looks like compile config issue. Can you reproduce with the example project?

**Comment by NoerNova** [comment] 2017-11-05 07:25
yes, I've continuous with this project after a while and my solutions is re-install 'react-native-fcm' module, re-link it and fix all file that show error.
(PS. sorry for late answer, if you haven figured out your problem yet ask me to show you my full solutions )

**Comment by evollu** [comment] 2017-11-05 14:38
cool closing this as original issue is solved

**Closed by evollu** 2017-11-05 14:38 UTC
Labels: question

**Comment by emmekappa** [comment] 2017-11-12 14:36
I'm having the exact same issue here, even reinstalling and relinking `react-native-fcm`.
