### ISSUE TITLE
Don't receive push notification when user kill app (Android & IOS)

### ISSUE THREAD

**Issue by thoth-nexlesoft** [evollu/react-native-fcm#542] opened 2017-09-05 12:47 UTC
Hi @evollu,
My app can receive push notifcation on fourground and background. But app don't receive push notification when user kill app. Can you help me?

```
"react-native-fcm": "^9.1.0"
"react": "16.0.0-alpha.12"
"react-native": "^0.47.2",
```
```
Environment:
  OS:  macOS Sierra 10.12.5
  Node:  8.1.2
  Yarn:  0.24.6
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

```

**Comment by evollu** [comment] 2017-09-05 13:21
what is your payload

**Comment by thoth-nexlesoft** [comment] 2017-09-06 03:00
![screen shot 2017-09-06 at 9 43 22 am](https://user-images.githubusercontent.com/25680402/30092213-ea6fbc1c-92e7-11e7-932c-66e51c981fc2.png)

I have enabled "background push" in xcode.

Pay load:

```
{
"message": {"content": "testing 1"}
}
```
I don't understand why my app has been notification when user kill app.

**Comment by thoth-nexlesoft** [comment] 2017-09-06 10:05
backend
```
const payload = {
    data: object,
    notification: {
      "sound": "default",
      "body" : object.content,
      "title" : object.title,
    }
  }
```
Now app can receive when user kill app, but app run foreground, app IOS receive 2 notifications when server push 1 time??? Can you help me? @evollu

**Comment by evollu** [comment] 2017-09-06 13:34
Did you open the app by clicking the notification? In that case 2 notif is expected. There is a flag in notification that use can use to differ them.

**Comment by thoth-nexlesoft** [comment] 2017-09-07 00:34
How do you use to flag in notification? (frontend or backend) Can you write example? @evollu

**Comment by evollu** [comment] 2017-09-07 11:57
`opened_from_tray` is true if user tapped the banner

**Comment by toadums** [comment] 2017-09-07 16:48
I was having this issue on android, adding `sound: default` in my notification payload from my server made it show up (and make a sound :D)

**Comment by jarbaspsf** [comment] 2017-09-08 02:05
I have the same problem. In background or foreground i receive a push notification, but when app is killed i got nothing.

My Payload is:
`{"notification": {"sound": "default", "title": "Some Title", "body": "message"}`

I guess i doing something wrong on the app side perhaps? Because i transform the push notification to a Local notification with: 


`
[...]
this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
            
          console.log('aqui')
            if(notif.fcm != null && notif.fcm.body != null){
              FCM.presentLocalNotification({
                vibrate: 500,
                title: (notif.fcm != null && notif.fcm.title != null) ? notif.fcm.title : "Message",
                body:  notif.fcm.body,
                priority: "high",
                show_in_foreground: true,                         
                icon: "ic_launcher"
              });
            }
[...]`

And I think that is not necessary right?

**Comment by juvasquezg** [comment] 2017-09-08 04:06
Hi,

The same, I Don't receive push notification when  the app is killed. README say

```
// NOTE: if you want to handle notifications when app is closed, put another handler outside of component lifecycle because components won't be initialized.
```

A simple example please.

Thank you!!

**Comment by jarbaspsf** [comment] 2017-09-09 15:59
Update guys, so is not related with the code, i managed to receive the push notification when i set my App to auto-start with the device. 

I had to make this manually in my device (Zenfone 2) so, there is a way to request permission or force the auto-start of a React Native app?

**Comment by evollu** [comment] 2017-09-09 16:07
@juvasquezg readme updated

**Comment by evollu** [comment] 2017-09-09 16:08
@thoth-nexlesoft can this issue be closed now?

**Comment by evollu** [comment] 2017-09-09 16:13
@jarbaspsf `<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />` should get the permission for you. unless your phone is some custom android system

**Comment by jarbaspsf** [comment] 2017-09-09 17:25
@evollu i'm already using this permissions on android manifest, i followed the entire setup, adding the permission, services etc. But the app is not in the list to auto start with the device. The device has Android 6.0.1 installed. I will try in another device. 

Anyway i need to force the auto start or at least, check if is possible to request to the user to make auto start happen. =/

**Comment by evollu** [comment] 2017-09-09 20:05
https://inspiretech.zendesk.com/hc/en-us/articles/207046683-Why-can-t-I-receive-push-notification-I-m-using-Asus-Phone-or-Xiao-Mi-phone-

asus and xiaomi auto declines auto start permission. 
someone mentioned a way to request it programmatically 
https://stackoverflow.com/questions/39366231/how-to-check-miui-autostart-permission-programatically
you may find a way for asus as well.
once the method are confirmed I can update the repo to support those

**Comment by pewh** [comment] 2017-09-10 03:15
I already follow that code on my xiaomi phone. What does it do is **only** show Autostart OS Settings and let user enable autostart on selected app, **not** enable autostart on selected app automatically.

Why some popular apps like FB and WhatsApp have autostart automatically? Does it do programmatically? No, these apps has been on whitelist **by vendor**. Other popular apps like Slack is not in whitelist, so user must enable manually.

AFAIK, the only option on this case is:
1. Alert user to enable autostart on first install (if phone is xiaomi, asus, oneplus, etc)
2. when click 'Okay', show autostart setting.

Currently, there is no way to check if my app is already on autostart or not programmatically.

And the bad news is: my app is crash when showing autostart programmatically on xiaomi :(

**Comment by evollu** [comment] 2017-09-10 16:50
checked some Chinese forums and looks like it is by design by like xiaomi, asus, oppo, Flyme etc so for "better bootup speed and battery life".
more details might be found here https://github.com/ttdevs/KillMe

One simple solution might be adding a Toast to ask users to enable auto start themselves.

**Comment by evollu** [comment] 2017-09-10 16:51
closing this as the original issue seems to be solved. feel free to reopen.

**Closed by evollu** 2017-09-10 16:51 UTC

**Comment by akash-cp** [comment] 2017-11-06 10:24
Any updates on how to take auto-start permission for phones like xiaomi, asus, etc. in react native ?

**Comment by evollu** [comment] 2017-11-06 16:08
@akash-cp I'm not planning to support these phones because I don't haven't any of those. PRs are welcomed

`How to list your app in white listed apps?` not possible. the vendor decides who gets whitelisted.

**Comment by iiitmahesh** [comment] 2017-11-19 13:17
I have same issue one plus mobile. @akash-cp  any update on this??

**Comment by tunbse05080** [comment] 2021-08-31 02:47
In some devices such as Xiaomi, lev, Samsung,... you must be enabled auto-start permission to run background service on the app.

Hope it is useful for you!
