### ISSUE TITLE
Remote notification is empty when I call FCM.getInitialNotification

### ISSUE THREAD

**Issue by daniel00k** [evollu/react-native-fcm#339] opened 2017-03-04 17:51 UTC
I am using react-native-fcm ^6.0.2, react native 0.41.2 on an android device.

This is the scenario:

In my app I have a class named LoadingScreen. This class is just waiting for a push notification to change to the next scene "FinalScreen". When the app is visible (foreground), if I send a push using the fcm console, the app receive that push and everything works perfect. 
The problem is:  if the app goes to sleep or goes to second plane, when I send the push, the device show me the push in the notifications area, but when I clicked in it, the app shows me the LoadingScreen and nothing happens. The "notif" object is almost empty. If I do something like notif.fcm(in the js console), it only contains the action key.

This is the code of the LoadingScreen.
````
componentDidMount() {
    _this     = this;
    prevState = this.props.prevState;
    
    //Set some stuff
    this.setState(this.state);

    this.notificationListener = FCM.on(FCMEvent.Notification, async (notif) => {
      
      if(notif.fcm.body !== undefined){
        Vibration.vibrate();
        Actions.chargeFinalStep({prevState: _this.state});  
      }    
    });

    FCM.getInitialNotification().then((notif)=>{
      console.log("FCM.getInitialNotification");
      console.log(notif)
    });

    this.refreshTokenListener = FCM.on(FCMEvent.RefreshToken, (token) => {
        console.log(token)
        // fcm token may not be available on first load, catch it here
    });
    }
````

Any help would be appreciated :)

**Comment by ddobby94** [comment] 2017-03-08 22:41
+1

**Comment by evollu** [comment] 2017-04-11 20:00
1. When app is in background, the notification goes in `FCM.on` callback. `getInitialNotification` won't have the value. To be clear `Initial` means launching the app, not opening the app. So I think the notification should trigger on callback. Check if it is the case.
2. App stops rendering couple seconds after going to background, so your code to change screen may be ignored. (however I think javascript itself is still live) Try to persist the state and change screen after AppState change.

**Comment by cmedinasoriano** [comment] 2017-06-06 16:22
I am getting undefined notification.  Using `FCM.getInitialNotification().then((notification) => {})`.  Do somebody knows why?

iOS 10.2
RN 0.44.0
React 16.0.0-alpha.6

**Comment by veedeo** [comment] 2017-06-11 14:41
@evollu If the app was opened from app icon and there was no new notification sent. what FCM.getInitialNotification() should return?
Because now it always returns empty notification with opened_from_tray: 1

**Comment by evollu** [comment] 2017-06-11 15:01
Depends on OS. It should return undefined or empty object.

**Comment by cmedinasoriano** [comment] 2017-06-11 15:03
@evollu But why do you think I always receive undefined, no matter if I open the app from the notification when it was completely closed or in background?

**Comment by evollu** [comment] 2017-06-11 15:22
@cmedinasoriano 
you should see it in initNotif when you `open the app from the notification when it was completely closed`
what os are you using

**Comment by cmedinasoriano** [comment] 2017-06-11 15:23
react-native-fcm 7.0.0
RN 0.44.0
React 16.0.0-alpha.6
iOS 10.2

**Comment by evollu** [comment] 2017-06-11 17:21
looking into it

**Comment by evollu** [comment] 2017-06-11 17:29
@cmedinasoriano should be fixed in 7.0.2. It is a bug caused by v7 refactoring

**Comment by cmedinasoriano** [comment] 2017-06-11 17:30
Awesome! Thanks!

**Comment by evollu** [comment] 2017-06-11 17:31
@cmedinasoriano LMK if it is fixed. then I will close the issue

**Comment by cmedinasoriano** [comment] 2017-06-11 19:21
@evollu Working perfect! Thanks!

**Closed** 2017-06-11 19:28 UTC

**Comment by Twinski** [comment] 2017-06-19 11:06
@evollu Hey! Seems to be not working for me.. :( 
I'm on 7.0.3 and if app is closed and click the push notification banner..

notif is "undefined" in: FCM.getInitialNotification().then((notif) => ...
Any idea what could be the matter? I did all the setup that was needed.

**Comment by beeglebug** [comment] 2017-06-23 16:06
I am also seeing this (7.0.3)

From a fresh install of the app, when I first open the app, I see this in my logs:
```
getInitialNotification: { opened_from_tray: 1, fcm: { action: null } }
```

And every subsequent opening of the app (from fully closed) I see this:
```
getInitialNotification: { opened_from_tray: 1, fcm: { action: 'android.intent.action.MAIN' }, profile: 0 }
```

I have not sent any notifications since installing the app.

**Comment by evollu** [comment] 2017-06-26 13:36
@beeglebug this is expected. The initial notification is who triggers the open. For android it is `android.intent.action.MAIN` is you open by clicking the app icon.
I expect people to look for particular custom field (like `type`) in notification and ignore the rest.

**Comment by evollu** [comment] 2017-06-26 13:37
@Twinski can you try the example project? you can schedule a local notification and test the banner

**Comment by beeglebug** [comment] 2017-06-26 14:36
@evollu I suppose that kind of makes sense although personally I would expect it to not trigger at all if the interaction didn't originate from a notification, but maybe that's just me

**Comment by AugustKarlstedt** [comment] 2017-06-28 03:17
I was expecting getInitialNotification to only be called if the app is opened from a notification as well. It's strange to me that it also is called when opened through the launcher.

**Comment by jqn** [comment] 2017-11-30 21:23
plus one

**Comment by Uysim** [comment] 2017-12-21 14:51
I still face the same issue. Did anyone found the solution?
