### ISSUE TITLE
"Module 'Firebase' not found" while building (iOS)

### ISSUE THREAD

**Issue by jaschaio** [evollu/react-native-fcm#826] opened 2018-03-02 10:30 UTC
I checked and the line causing the error was just updated yesterday https://github.com/evollu/react-native-fcm/commit/da07b4d2d769eb112a33b696efa324cf2892ec1d

Not sure what I am missing.

react-native: 0.53.3
react-native-fcm: ^14.0.0

**Comment by jaschaio** [comment] 2018-03-02 10:41
Replacing the `@import Firebase` line with

    @import FirebaseCore;
    @import FirebaseMessaging;
    @import FirebaseInstanceID;

Seems to work for me.

**Comment by evollu** [comment] 2018-03-02 16:43
`@import Firebase;` is how FCM official document suggests.
Probably you are missing something in pod install.

**Comment by douglasjunior** [comment] 2018-03-02 21:04
Same problem here after update the library, I'm not using cocoapods.

**Comment by douglasjunior** [comment] 2018-03-02 21:14
I think that `@import Firebase;` is not supported for all use cases yet.

In README file that is shipped with Firebase Library:

> 8. Drag the `Firebase.h` header in this directory into your project. This will
>   allow you to `#import "Firebase.h"` and start using any Firebase SDK that you
>   have.

[README.md.zip](https://github.com/evollu/react-native-fcm/files/1776584/README.md.zip)

**Comment by evollu** [comment] 2018-03-03 01:43
let me check. it is such a headache.

**Comment by evollu** [comment] 2018-03-03 01:52
@douglasjunior can you try add `module.modulemap` file next to the header file?
```
module Firebase {
  export *
  header "Firebase.h"
}
```

**Comment by douglasjunior** [comment] 2018-03-03 14:02
I also suffer with these problems in a project that I maintain douglasjunior/react-native-keyboard-manager#20 😄 

About the `module.modulemap` file, is something like this?

![image](https://user-images.githubusercontent.com/1512341/36935127-46c64802-1ed2-11e8-8885-29dcbb8b249a.png)

Not worked too.

**Comment by vic9511** [comment] 2018-03-04 17:56
Same problem here, I'm using cocoapods.

**Comment by andrejunqueira1** [comment] 2018-03-05 02:32
same problem :(

**Comment by dotansimha** [comment] 2018-03-05 10:02
same :(

**Comment by evollu** [comment] 2018-03-05 15:19
@vic9511 cocoapod should not have problem. the example project is using cocoapods without issue

**Comment by dotansimha** [comment] 2018-03-05 15:24
@evollu 
I'm using cocoapods in my project. Updated to the latest version of `react-native-fcm` and since then I'm getting this error. Also tried to `pod update` and it didn't help.
Tried to clean everything and reinstall again - still getting this error. at the moment, the only possible workaround I found is to revert to v13...

**Comment by evollu** [comment] 2018-03-05 15:30
@dotansimha can you compare the project with the example project? that works without issue

**Comment by vic9511** [comment] 2018-03-05 18:49
@evollu yes you right, sorry for that. It seems that I had a conflict with linkings.

@dotansimha we fixed that closing xcode and deletting ios/Pods and Podfile.lock

Also delete node_modules and run yarn again and run pod install as well

And re-check again Manual linkings https://facebook.github.io/react-native/docs/linking-libraries-ios.html

Maybe you can also try react-native unlink react-native-fcm to prevent other linkings conflict (although it should not affect)

Hope this can help you!

**Comment by evollu** [comment] 2018-03-05 19:20
added example of manual integration under `no-pod` branch. also updated readme a bit

**Comment by douglasjunior** [comment] 2018-03-05 20:07
Adding `User Header Search Paths` and creating `module.modulemap` made it work. Thanks.

**Comment by evollu** [comment] 2018-03-05 20:30
@jaschaio issue seems to be solved. can i close this?

**Comment by bkvirendra** [comment] 2018-03-08 17:53
Replacing `@import FirebaseCore` with worked for me.

```
#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
#import <FirebaseInstanceID/FirebaseInstanceID.h>
```

**Comment by evollu** [comment] 2018-03-09 00:06
@bkvirendra this is not a solution.
I'm not going to change it back to use `#import`

**Comment by kcfgl** [comment] 2018-03-09 10:27
@vic9511 I've been struggling with this same issue for a few hours after upgrading to latest version. I've tried the manual route and the Pods route. Followed your steps and deleted nod_modules, pods, reran everything but still failing with Module Firebase not found.  

Even though it wasn't in your steps, I tried adding the modulemap file to Frameworks. Didn't matter. Is there any other step - maybe in the manual linking or elsewhere - that I could be missing? Thanks!

**Comment by Titozzz** [comment] 2018-03-12 17:37
Hello, @evollu It looks like the fix to the podspec file was working for 11.3 but not anymore, I'll try to fix it so we can use the new syntax

**Comment by evollu** [comment] 2018-03-12 21:41
@Titozzz pod solution has been working fine for me. Can you post a public repo that has the issue?

**Comment by Titozzz** [comment] 2018-03-13 10:33
Will do asap.

**Comment by brzonsea** [comment] 2018-03-14 11:04
I am using cocoapods and am also facing the same issue. I tried to above solutions, I also tried reinstalling and re-doing my manual linking. But still I find the 'Module Firebase not found' error.
Also, 
@import FirebaseCore;
@import FirebaseMessaging;
@import FirebaseInstanceID;
replacing the line with this just simply gives out 'Module FirebaseCore not found' instead.

**Comment by bkvirendra** [comment] 2018-03-14 11:26
@brzonsea can you try using this instead:

```
#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
#import <FirebaseInstanceID/FirebaseInstanceID.h>
```

**Comment by brzonsea** [comment] 2018-03-14 11:35
@bkvirendra 
I tried it just now, and "'FirebaseCore/FirebaseCore.h' file not found" is the error message now. 
Am I missing some critical step in the setup process? I think I've read the README quite thoroughly, but what are these FirebaseCore, FirebaseMessaging, FirebaseInstanceID stuff?

**Comment by bkvirendra** [comment] 2018-03-14 11:42
@brzonsea do you have the `pod 'FirebaseMessaging'` in your Podfile?

Also, can you check if you have the following in `Header Search Paths`,

<img width="808" alt="screen shot 2018-03-14 at 11 42 03 am" src="https://user-images.githubusercontent.com/1097043/37400415-c9455c0c-277c-11e8-9428-8434915da5ea.png">

**Comment by brzonsea** [comment] 2018-03-14 13:07
@bkvirendra 
Thanks for the detailed image! I didn't have the above Header Search Paths, so I added them.
But the problem is not solved yet... And yes, I have the `pod 'FirebaseMessaging'` in my Podfile

**Comment by bkvirendra** [comment] 2018-03-14 13:30
@brzonsea can you paste the detailed versions & the traceback for the exception?

**Comment by brzonsea** [comment] 2018-03-14 13:38
@bkvirendra 
My versions are
react-native: 0.51.1
react-native-fcm: ^14.1.0
cocoapods: 1.4.0

And this is the error message:

In file included from /Users/namungkim/Projects/Classum/ClassumReactNativeApp/node_modules/react-native-fcm/ios/RNFIRMessaging.m:1:
/Users/namungkim/Projects/Classum/ClassumReactNativeApp/node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by Titozzz** [comment] 2018-03-14 13:39
Guys, I think we have 2 separate issues here, on my side i'm taking about people linking the library with cocoapods with this kind of podfile:

```
target 'test' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTSettings',
    'RCTAnimation',
    'RCTLinkingIOS',
    # Add any other subspecs you want to use in your project
  ]

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  pod 'react-native-google-signin', :path => '../node_modules/react-native-google-signin'
  pod '....'
end
```
---

However you guys are using the podfile to only link the native dependencies manually:

---
```
target 'test' do
  pod 'Firebase/Messaging'
  pod '....'
end
```

The point of using method n°1 is that you only link using the cli and the dependencies are specified inside the podspec file.  cc @evollu

**Comment by brzonsea** [comment] 2018-03-14 16:42
@bkvirendra 
It seems I was using the firebase web sdk, so prior native settings for firebase wasn't done. After installing react-native-firebase, and following your advice it is working now! Thanks!

**Comment by evollu** [comment] 2018-03-15 13:51
@brzonsea for everyone having issue with
`#import <FirebaseCore/FirebaseCore.h>`
You are not having the latest version of the repo. This line has been updated by following
https://github.com/evollu/react-native-fcm/blob/v14.0.1/ios/RNFIRMessaging.h#L4

**Closed by evollu** 2018-03-15 13:51 UTC

**Comment by Titozzz** [comment] 2018-03-15 14:46
@evollu Issue is not fixed for users using cocoapods like me tho... Right now I did this:

in my postinstall hooks: 
"sed -i'' -e 's/@import Firebase;/@import FirebaseCore;@import FirebaseMessaging;@import FirebaseInstanceID;/' ./node_modules/react-native-fcm/ios/RNFIRMessaging.h"

**Comment by evollu** [comment] 2018-03-15 16:16
@Titozzz please post a github repo with the issue.

**Comment by dotansimha** [comment] 2018-03-19 20:19
@Titozzz same here...

**Comment by Titozzz** [comment] 2018-03-20 10:47
https://github.com/Titozzz/ReactNativeStarterCocoapods

To test: 
```
yarn
cd ReactNativeStarterCocoapods
pod install
```
@evollu there you go, if you don't run yarn fix-react-native-fcm, the build will fail.

**Comment by evollu** [comment] 2018-03-20 15:40
@Titozzz will try. thanks

**Comment by evollu** [comment] 2018-03-20 16:23
@Titozzz The problem is it is trying to build react-native-fcm as a pod project but it doesn't know how to load module map from peers. it is really tricky. do you have to do it this way?

**Comment by Titozzz** [comment] 2018-03-20 16:36
Yes and i'm not alone, the thing is, with react native that once you add a podfile to your project, it will try to link that way and only that way. I could link manually, I could rename my podfile during the link, but I'd rather try to find a solution so that everyone is happy

**Comment by evollu** [comment] 2018-03-20 17:12
@Titozzz how about removing podspec file?

**Comment by Titozzz** [comment] 2018-03-20 17:25
but does it work if you only put 
```
@import FirebaseCore;
@import FirebaseMessaging;
@import FirebaseInstanceID;
```
?

**Comment by evollu** [comment] 2018-03-20 17:31
no either

**Comment by dotansimha** [comment] 2018-03-20 17:33
For me, running this as script in `postinstall` works:
```
#/bin/sh

# Workaround for: https://github.com/evollu/react-native-fcm/issues/826
sed -i'' -e 's/@import Firebase;/\
#import <FirebaseCore\/FirebaseCore.h>;\
#import <FirebaseMessaging\/FirebaseMessaging.h>;\
#import <FirebaseInstanceID\/FirebaseInstanceID.h>;/' ./node_modules/react-native-fcm/ios/RNFIRMessaging.h
```

**Comment by Titozzz** [comment] 2018-03-20 17:41
That's weird, because on the example repo I gave you it works for me (you can patch with yarn fix-react-native-fcm). Can you check your cocoapods version and be sure you are ^1.4.0 ?

**Comment by evollu** [comment] 2018-03-20 17:51
```
#if __has_include(<Firebase.h>)
#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
#import <FirebaseInstanceID/FirebaseInstanceID.h>
#else
@import Firebase;
#endif
```

**Comment by evollu** [comment] 2018-03-20 17:54
yep seems to be working for every cases. let me know

**Comment by Titozzz** [comment] 2018-03-20 22:33
Sorry I did not pay attention to you when you said you were using Cocoapods 1.3. Cocoapods 1.4 released this new feature allowing us to use static_frameworks (http://blog.cocoapods.org/CocoaPods-1.4.0/) that I specified in the podspec file of this repo. So I guess our differences comes from here. Let me try your syntax.

**Comment by evollu** [comment] 2018-03-20 23:30
@Titozzz anyway my code above should work for you. 
it is released in latest item

**Comment by hjJunior** [comment] 2018-03-22 13:10
@evollu where can I make this changes?

**Comment by karanhashedin** [comment] 2018-05-29 14:59
#if __has_include(<Firebase.h>)
#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseMessaging/FirebaseMessaging.h>
#import <FirebaseInstanceID/FirebaseInstanceID.h>
#else
@import Firebase;
#endif

gives error of module firebase not found...
I have read all above comments and implemented all
but none worked for me... 
I have added path of module.modulemap to header search path but it didn't help
I have not used cocoapods.
Please help asap
Thanks in advance

**Comment by hientuong** [comment] 2018-06-07 05:02
@jaschaio: it's work for me. Thank u.

**Comment by jissree** [comment] 2018-07-09 07:12
If you're using objective-c just drag the file firebase.h into your project

**Comment by freddyfernando93** [comment] 2018-07-23 17:22
In my case, i just removed react-native-fcm then cleaned cache, reinstalled it again and it worked. I'm not using cocoapods.
```
npm uninstall react-native-fcm
npm install --reset-cache
npm install react-native-fcm --save
react-native link
```

**Comment by tsku** [comment] 2018-08-10 18:27
I saw this error due to a missed instruction in the terminal output after installing the pod:

"Please close any current Xcode sessions and use `<ProjectName>.xcworkspace` for this project from now on.
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed."

Opening the new .xcworkspace fixed it for me.

**Comment by hungvu193** [comment] 2018-08-24 10:39
such a headache, i'm still facing this issue on Xcode 9.4, "react-native-fcm": "11.2.0". Any solutions so far 🗡

**Comment by yuber1792** [comment] 2018-12-12 14:58
Hi

Español:

tenia una version antigua de firebase analytics  la actualiza, luego **npm install**  después **pod install**   para terminar luego agregando estas lineas.

Ingles:

had an old version of firebase analytics update it, then ** npm install ** then pod install to finish then adding these lines.


#import <FirebaseCore/FirebaseCore.h>
#import <FirebaseAnalytics/FIRAnalytics.h>

**Comment by vickkeshri** [comment] 2019-11-06 06:31
I found the problem with pod 'RNFirebase', :path => '../node_modules/react-native-firebase'.
Solution:
I commented pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
```
react-native link
cd ios
pod install (install all firesbase modules)
cd ..
npm install or yarn install
```
Then, try adding @import Firebase
react-native run-ios

It worked for me..!!Hope this help you guys.!

**Comment by JCYOUNG123** [comment] 2020-02-27 04:46
> @import FirebaseCore;
> @import FirebaseMessaging;
> @import FirebaseInstanceID;

First two no problem, but the third one shows error Module 'FirebaseInstanceID' not found.

**Comment by dsouksavatd** [comment] 2020-12-31 08:10
1. you have to install @react-native-firebase/app package instead of @react-native-firebase
2. pod install
3. yarn ios
