### ISSUE TITLE
large_icon now showing when application is in Background or Closed

### ISSUE THREAD

**Issue by roberto-rodriguez** [evollu/react-native-fcm#566] opened 2017-09-15 15:42 UTC
I am sending this:

custom_notification: {  title: 'a', body: 'b', show_in_foreground: true, large_icon:'https://image.freepik.com/free-icon/small-boy-cartoon_318-38077.jpg' }

It displays the image when the application is in foreground, but not when the application is in Background or closed.

**Comment by evollu** [comment] 2017-09-15 15:54
do you mean there is no notification at all or just the image is not showing?
does regular notification work in background?

**Comment by roberto-rodriguez** [comment] 2017-09-15 17:01
Hi, thanks for the quick response, really appreciated, and congrats for the lib.. it's awesome.

Yes the notification is showing, but is not considering the image I am sending, it displaying the one I was displaying before I add the large_icon property.
BTW I am using your sample app, testing in Android, device Samsung Galaxy 5.

**Comment by evollu** [comment] 2017-09-15 17:35
ok the issue is it is trying to make network request on main thread on download the image. finding solution now

**Comment by roberto-rodriguez** [comment] 2017-09-15 17:51
Thanks!!

**Comment by evollu** [comment] 2017-09-15 18:21
fixed in v9.3.0

**Comment by roberto-rodriguez** [comment] 2017-09-15 18:48
Thank you very much.
When will be available?

**Comment by evollu** [comment] 2017-09-15 18:56
it is already. also sub_text is in example as well

**Closed** 2017-09-21 00:11 UTC
