### ISSUE TITLE
Cant use with Expo and create-react-native-app

### ISSUE THREAD

**Issue by ntvinhit** [evollu/react-native-fcm#1033] opened 2018-08-28 09:44 UTC
I use "create-react-native-app" to create new react native app, then I use Expo to build and deploy the app.
But there is no android or iOS directory inside to copy google-services.json  to.
I tried to run without copying it, then "Cannot read property 'getInitialNotification' of undefined" when I run FCM.getInitialNotification();
So, how can I still use this lib without android directory?
I tried to eject but I don't want to use Expo Kit.

I use Galaxy S7 Edge with Android 8.0.0, React Native version 0.55.2, react-native-fcm version 16.2.0

Please help me
Thanks

**Comment by evollu** [comment] 2018-08-28 17:44
does it provide some documentation on how to add 3rd party modules? there must be a way

**Comment by christianchown** [comment] 2018-10-01 08:35
Duplicate of  #1029 and #1044

@ntvinhit, you will need to eject, and then follow the steps in 
- https://github.com/evollu/react-native-fcm#android-configuration and 
- https://github.com/evollu/react-native-fcm#ios-configuration as in

**Closed** 2020-08-21 08:02 UTC
