### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference

### ISSUE THREAD

**Issue by edy** [evollu/react-native-fcm#137] opened 2016-09-30 16:49 UTC
react-native 0.34
react-native-fcm 2.2.0
Android 6 on a Moto G3

On a Production Build, firebase-crash catched a NullPointerException. Unfortunately i cannot provide more details how and when this happened (running in foreground or background).

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
com.evollu.react.fcm.FIRMessagingModule.getInitialNotification (FIRMessagingModule.java:54)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke (BaseJavaModule.java:319)
com.facebook.react.cxxbridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:158)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:746)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:148)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:196)
java.lang.Thread.run (Thread.java:818)
```

**Comment by evollu** [comment] 2016-09-30 21:41
looks like you are trying to get intent before react native has fully started activity
`getCurrentActivity()` return null.
When do you call this method?

**Comment by edy** [comment] 2016-09-30 22:09
I call `FCM.getInitialNotification().then(...)` in `componentDidMount()` of my main component. Is it not the best place call is there?

**Comment by evollu** [comment] 2016-09-30 22:17
it is. i've released a version to prevent crash but you will get null when activity is null so app won't crash
however i'm still curious about the cause.

**Comment by edy** [comment] 2016-09-30 22:20
thank you

**Comment by evollu** [comment] 2016-10-07 01:18
closing this. please reopen if you see null activity again

**Closed** 2016-10-07 01:21 UTC
