### ISSUE TITLE
fcm token not available on first load react native (android) Please help me with eample

### ISSUE THREAD

**Issue by azamkth** [evollu/react-native-fcm#652] opened 2017-11-16 13:58 UTC

**Comment by evollu** [comment] 2017-11-17 03:04
it is normal. FCM token takes a while to be returned by firebase. listen on tokenRefresh handler

**Comment by azamkth** [comment] 2017-11-17 08:22
thanks @evollu could you please give me the example how  can use tokenRefresh ?

**Comment by alexdunne** [comment] 2017-11-17 09:38
@azamkth Looking at the Usage example in the README it looks like you need to be using `FCMEvent.RefreshToken`.

```
FCM.on(FCMEvent.RefreshToken, token => {
  console.log(token);
});
```

**Comment by azamkth** [comment] 2017-11-17 09:40
@alexdunne getting Cannot read property 'RefreshToken' of undefined

**Comment by alexdunne** [comment] 2017-11-17 09:40
You need to import FCMEvent

```
import FCM, { FCMEvent } from "react-native-fcm";
```

**Comment by azamkth** [comment] 2017-11-17 09:41
i did but same error

**Comment by alexdunne** [comment] 2017-11-17 09:44
Not sure then, just set it up myself at it works.

What if you `console.log(FCMEvent);`

You should see something like

```
{
  "DirectChannelConnectionChanged": "FCMDirectChannelConnectionChanged",
  "Notification": "FCMNotificationReceived",
  "RefreshToken": "FCMTokenRefreshed"
}
```

**Comment by azamkth** [comment] 2017-11-17 09:50
i did and getting undefined

**Comment by alexdunne** [comment] 2017-11-17 10:05
I've created an expo example https://snack.expo.io/H1RnmEnkf

If you look at the preview you can see the output of `FCMEvent.RefreshToken` and `JSON.stringify(FCMEvent)`.

**Comment by azamkth** [comment] 2017-11-17 10:16
right but when i did console.log(FCMEvent); I got "undefined". Could you please give me any suggestion why i am getting this ?

**Comment by alexdunne** [comment] 2017-11-17 10:19
Can you show the code you're working with? If your code looks like the expo example then it should work.

**Comment by azamkth** [comment] 2017-11-17 10:20
'use strict';
import React from 'react';
import ReactNative from 'react-native';
import FCM, { FCMEvent } from 'react-native-fcm';
componentDidMount: function() {
        console.log(FCMEvent);
},

**Comment by alexdunne** [comment] 2017-11-17 10:25
I'm not sure then. Maybe it's to do with the version you're using? I'm not familiar enough with the library to know for sure.

What do you get if you `console.log(FCM)`?

Also not that it should matter but try moving the `console.log`s directly underneath your `import`s.

**Comment by azamkth** [comment] 2017-11-17 10:41
console.log(FCM) giving bellow ouput

{ getInitialNotification: [Function],
 getFCMToken: [Function],
 requestPermissions: [Function],
 presentLocalNotification: [Function],
 scheduleLocalNotification: [Function],
 getScheduledLocalNotifications: [Function],
 cancelLocalNotification: [Function],
 cancelAllLocalNotifications: [Function],
 removeDeliveredNotification: [Function],
 removeAllDeliveredNotifications: [Function],
 setBadgeNumber: [Function],
 getBadgeNumber: [Function],
 on: [Function],
 subscribeToTopic: [Function],
 unsubscribeFromTopic: [Function],
 send: [Function] }

**Comment by alexdunne** [comment] 2017-11-17 10:48
What version of the library are you using?

**Comment by azamkth** [comment] 2017-11-17 10:52
react-native-fcm": "^2.5.6" (in package.jason)

**Comment by alexdunne** [comment] 2017-11-17 10:58
Ah. That will be why then. The current version is [10.0.3](https://github.com/evollu/react-native-fcm/releases/tag/v10.0.3).

Looking at the 2.5.6 version of [index.js](https://github.com/evollu/react-native-fcm/blob/v2.5.6/index.js) it looks like the event map isn't exported hence why you're getting undefined.

Sadly, I haven't used that version so I'm not sure what your issue could be.

**Comment by azamkth** [comment] 2017-11-17 11:01
Could you tell me how i can update react-native-fcm ?

**Comment by alexdunne** [comment] 2017-11-17 11:04
Depending on if you're using [npm](https://docs.npmjs.com/cli/update) or [yarn](https://yarnpkg.com/lang/en/docs/cli/upgrade/).

```
npm update react-native-fcm
```

or

```
yarn upgrade react-native-fcm
```

**Comment by azamkth** [comment] 2017-11-17 11:06
ok i will get back to you soon. thanks a lot for your help. one more question this update will not make any effect with current funcationality.

**Comment by alexdunne** [comment] 2017-11-17 11:07
I expect as there have been several major versions since 2.5.6 some things will be different. However, I'm not certain what specifically will have changed.

**Comment by azamkth** [comment] 2017-11-17 14:31
@alexdunne I am using react-native 0.39.2 so for RN < 0.40.0, use react-native-fcm@2.5.6 that' why I was using this version. any solution?

**Comment by evollu** [comment] 2017-11-17 17:04
@azamkth you can use hardcode string `'FCMTokenRefreshed'`

**Comment by azamkth** [comment] 2017-11-17 18:12
@evollu could you please give me the example how i can use hardcode string 'FCMTokenRefreshed' ? and where i should use ?

**Comment by evollu** [comment] 2017-11-18 04:20
```
FCM.on('FCMTokenRefreshed', token => {
  console.log(token);
});
```

**Comment by azamkth** [comment] 2017-11-18 23:12
@evollu getting error:  FCM event must be "refreshToken" or "notification

**Comment by evollu** [comment] 2017-11-19 04:34
try delete the app and reinstall. You may or may not get `refreshToken` event depending on how quickly your device gets FCM token. If your device gets token before JS gets bootstrapped or your device already has a token, the event won't be called.

**Comment by imbudhiraja** [comment] 2017-11-20 04:28
@azamkth Here is my code using react-native 0.39.2 & react-native-fcm 2.5.6.

      FCM.getFCMToken().then(token => {
        console.log("deviceToken ",token)
      });
     
     FCM.getInitialNotification().then(notification=>{
      // Push Tap Navigation
     });

     this.notificationUnsubscribe = FCM.on('notification', (notification) => {
            // there are two parts of notif. notif.notification contains the notification payload, notif.data contains data payload
        if(notification.opened_from_tray){
         // Push Tap Navigation
        }
      });
      
      this.refreshUnsubscribe = FCM.on('refreshToken', (token) => {
          console.log("refreshToken ",token)
          // fcm token may not be available on first load, catch it here
      });

**Comment by azamkth** [comment] 2017-11-21 16:25
I tried but the problem is still there (fcm token not available on first load). I need to get device token on login view. But unfortunately  it seems that not possible so far.

**Comment by ivanFullStackSenior** [comment] 2018-01-15 14:36
Check your internet connection. If you without it you cannot to take token.

**Comment by liqing1990** [comment] 2018-02-19 14:44
@azamkth 
I am the same problem, there are ways to solve it？

**Comment by liqing1990** [comment] 2018-02-19 15:28
@evollu I am the same problem..
```
FCM.on('FCMTokenRefreshed', token => {
  console.log(token);
}); 
```
it is not triggering!!!....
my version: 
"react-native": "0.51.0",
 "react-native-fcm": "^13.3.1",

**Comment by fidoe** [comment] 2018-03-10 19:55
Same issue, nothing triggering on APK build.  Works fine on debug.

**Comment by ASteinheiser** [comment] 2018-05-03 19:11
@evollu Is this fixed now as per #930 ?

**Comment by evollu** [comment] 2018-05-07 15:00
@ASteinheiser Android should have been fixed long time ago.

**Comment by singhiskamal** [comment] 2018-08-22 13:04
@evollu I am using v16.1.0 with RN v0.54.4 and 
FCM.getFCMToken().then(token => {
    console.log("token",token)
  });
The token is always blank on debug and prod release.Please help. Thanks in advance.

**Comment by evollu** [comment] 2018-08-28 17:28
closing this due to inactivity
@singhiskamal can you reproduce using the example project?

**Closed by evollu** 2018-08-28 17:28 UTC
