### ISSUE TITLE
RefreshToken listener not getting called [iOS]

### ISSUE THREAD

**Issue by ASteinheiser** [evollu/react-native-fcm#930] opened 2018-05-03 00:38 UTC
So getFCMToken() is 'undefined' on first open as expected, however my RefreshToken listener, which should solve the undefined issue, is not getting called. I've also tried replacing the FCMEvent parameter with the string in the comment, as per some issue that stated the string is the correct usage. Neither way worked.

Any ideas?

**Tested on:**
iPad iOS v11.3.1
react-native: 0.52.2
react-native-fcm: 14.1.3

**Here is my component:**
```javascript
import React, { Component } from 'react';
import { AppState }         from 'react-native';
import FCM, { FCMEvent }    from 'react-native-fcm';

import { setCookie } from '../functions/set-cookie.js';

export default class PushNotification extends Component {
  componentDidMount() {
    FCM.requestPermissions(); // for iOS
    FCM.getFCMToken().then(token => {
      console.log("TOKEN (getFCMToken)", token);
      setCookie(token);
    });

    FCM.getInitialNotification().then(notif => {
      // console.log("INITIAL NOTIFICATION", notif);
      if(notif.path) { // if you want to redirect to a page
        this.props.updatePath(notif.path);
      }
    });

    this.notificationSubscribe = FCM.on(FCMEvent.Notification, notif => { // 'FCMNotificationReceived' is new api?
      // console.log("notification: ", notif);
      if (notif && notif.local_notification) return;
      if (AppState.currentState === 'active') { // if app is in foreground
          // TODO: add local notifications
          console.log('active and got notification');
      }
      else if(notif.path) { // if you want to redirect to a page
        this.props.updatePath(notif.path);
      }
      this.sendRemote(notif);
    });
    // this method call when FCM token is update(FCM token update any time so will get updated token from this method)
    this.tokenRefreshed = FCM.on(FCMEvent.RefreshToken, token => { // 'FCMTokenRefreshed' is new api?
      console.log("TOKEN (tokenRefreshed)", token);
      setCookie(token);
    });
  }

  // This method display the notification on mobile screen.
  sendRemote(notif) {
    console.log('send remote notification');
    FCM.presentLocalNotification({
      title: notif.title,
      body: notif.body,
      priority: "high",
      click_action: notif.click_action,
      show_in_foreground: true,
      local: true
    });
  }

  componentWillUnmount() {
    this.notificationSubscribe.remove();
    this.tokenRefreshed.remove();
  }

  render() {
    return null;
  }
}
```

**Comment by ASteinheiser** [comment] 2018-05-03 01:10
I would also like to note that this was confirmed to work yesterday, but today I experienced these issues.

I also found a dirty workaround for the time being, by checking again for the token if it's undefined initially:
```javascript
FCM.getFCMToken().then(token => {
      if(!token) {
        setTimeout(() => {
          FCM.getFCMToken().then(token => {
            console.log("TOKEN (getFCMToken)", token);
            setCookie(token);
          });
        }, 3000);
      } else {
        console.log("TOKEN (getFCMToken)", token);
        setCookie(token);
      }
    });
```

**Comment by evollu** [comment] 2018-05-03 01:46
this might be caused by event firing before JS is getting bootstrapped.
I have this fix for the notification event 
https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.m#L247
you can try to do a PR for this https://github.com/evollu/react-native-fcm/blob/master/ios/RNFIRMessaging.m#L452

**Comment by evollu** [comment] 2018-05-03 18:29
fixed in v14.2.0

**Closed by evollu** 2018-05-03 18:29 UTC

**Comment by xavi** [comment] 2018-05-10 13:41
Couldn't it be that the reason why the RefreshToken listener is not called is because `RNFIRMessaging` implements
`messaging:didRefreshRegistrationToken:`
https://github.com/evollu/react-native-fcm/blob/v14.2.1/ios/RNFIRMessaging.m#L458-L461
but,  looking at the latest Firebase docs, it seems it should implement
`-messaging:didReceiveRegistrationToken:`
instead?
https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Protocols/FIRMessagingDelegate
(I can't find any reference to `messaging:didRefreshRegistrationToken` callback in Firebase docs.)

**Comment by GuillaumeLachaud** [comment] 2018-06-21 21:45
I can reproduce this on `15.0.2`, with Firebase SDK 15. `getFCMToken()` returns `undefined` on first launch,  RefreshToken never fires and killing/reopening the app delivers the token through `getFCMToken()`
